---
title: "sandbox"
format: pdf
editor: visual
---


```{r}
#| label: data
#| eval: false
#| include: false

mat_names <- list('ay' = paste0('ay_', 1969:1976), 
  'age' = paste0('age_', 12 * 1:8))

# B-S Exhibit A
incd <- matrix(data = c(
  c(2897, 4828, 5455, 8732, 11228, 8706, 12928, 15791),
  c(5160, 10707, 11942, 18633, 19967, 33459, 48904, NA)), 
  nrow = 8, byrow = FALSE, dimnames = mat_names)

# B-S Exhibit C
paid_clsd <- matrix(data = c(
  c(402, 110, 706, 161, 724, 518, 517, 525),
  c(539, 919, 1115, 862, 541, 1394, 1494, NA)), 
  nrow = 8, byrow = FALSE, dimnames = mat_names)

# B-S Exhibit D
open <- matrix(data = c(
  c(749, 660, 878, 1043, 1088, 1033, 1138, 1196),
  c(840, 957, 1329, 1561, 1388, 1418, 1472, NA)), 
  nrow = 8, byrow = FALSE, dimnames = mat_names)

# B-S Exhibit E
paid <- matrix(data = c(
  c(125, 43, 295, 50, 213, 172, 210, 209),
  c(406, 529, 1147, 786, 833, 1587, 1565, NA)), 
  nrow = 8, byrow = FALSE, dimnames = mat_names)

avg_clsd <- paid / paid_clsd * 1e3 |> round()

avg_case <- ((incd - paid) / open * 1e3) |> round()
```

```{r}
#| eval: false
#| include: false
#| paged-print: true
# Berquist-Sherman Exhibit A
incd
```

```{r}
#| eval: false
#| include: false
ay <- 1969:1976
case <- c('ay_1969' = 3817, avg_case[2:8 ,1])
model <- lm(formula = log(case) ~ ay)

# Indicated Trend is 15.3%, See B-S Exhibit B
(model$coefficients['ay'] |> exp() - 1 ) |> 
  easyr::fmat(type = '%', digits = 1)

# Selected Trend is 15.0%, See B-S Section III

adjusted_case <- matrix(data = 
    c(avg_case[8, 1] / 1.15 ^ (7:0), # age 12
      avg_case[7, 2] / 1.15 ^ (6:0), NA), #age 24
  ncol = 2, byrow = FALSE)

# Restated Incurred - See B-S, Exhibit F
(adjusted_case * open) / 1e3 + paid

```
